pull_request_rules:
  - name: automatic merge when CI checks pass and at least one approved review
    conditions:
        
      - label = automerge
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: squash
        commit_message_template: |
            {{ title }} (#{{ number }})

            {{ body }}

            {% for user in approved_reviews_by %}
            Approved-By: {{user}}
            {% endfor %}