pull_request_rules:
  - name: Automatic merge
    description: Merge when PR approved by at least one reviewer and has label automerge
    conditions:
      - '#approved-reviews-by>=1'
      - label = automerge
    actions:
      merge: 
