pull_request_rules:
  - name: dismiss reviews when new commits are pushed, if the label "re-review" is present<img src=0>.
    conditions:
      - base=main
      - label=re-review
    actions:
      dismiss_reviews:
